version: '3.1'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - GO_ENV=production
      - DATABASE_URL="postgres://buffalo:password@172.16.238.10:5432/modelsdemo_production?sslmode=disable"
    depends_on:
      - db
    networks:
      - app_net
    ports:
      - 3000:3000

  db:
    image: postgres
    environment:
      POSTGRES_USER: buffalo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modelsdemo_production
    networks:
      app_net:
        ipv4_address: 172.16.238.10

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24